#!/bin/bash

mode=$1
if [ "x$mode" = "x" ]; then
    mode=start
fi

. /etc/jrs/jrs.conf
host=`hostname`

case "$mode" in

    start)
        if [ $host = $master ]; then
            $jrsbin -n -s $secret -l $((port + 1)) -p ${pidpath}-master.pid
        fi

        grep -q $host $nodelist
        if [ $? -eq 0 ]; then
            $jrsbin -d -s $secret -l $port -p ${pidpath}-daemon.pid
        fi

        ;;

    stop)
        if [ -f ${pidpath}-master.pid ]; then
            kill `cat ${pidpath}-master.pid`
        fi
        if [ -f ${pidpath}-daemon.pid ]; then
            kill `cat ${pidpath}-daemon.pid`
        fi
        sleep 1
        if [ -f ${pidpath}-master.pid ]; then
            kill -9 `cat ${pidpath}-master.pid`
        fi
        if [ -f ${pidpath}-daemon.pid ]; then
            kill -9 `cat ${pidpath}-daemon.pid`
        fi

        ;;

    restart)
        $1 stop
        $1 start
        ;;
esac

